language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: CMAKE_OS=linux
      script: tools/travis/build_cmake.sh

cache:
  directories:
    - $HOME/.ccache
    - $HOME/bazel-cache
    - $HOME/gopath/bin
