language: cpp
os: linux
dist: trusty
sudo: false

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.8.1/bazel-0.8.1-installer-linux-x86_64.sh
  - chmod +x bazel-0.8.1-installer-linux-x86_64.sh
  - ./bazel-0.8.1-installer-linux-x86_64.sh --user

script:
  - bazel build --noshow_progress -k //...
  - bazel test --noshow_progress -k //...
  - ./format.sh
